CREATE or REPLACE FUNCTION LOAD_BLOB_FROM_FILE(FILENAME VARCHAR2, DIRECTORYNAME VARCHAR2)
    RETURN BLOB
  IS
    FILECONTENT BLOB := NULL;
    SRC_FILE BFILE := BFILENAME(DIRECTORYNAME,FILENAME);
    OFFSET NUMBER := 1;
  BEGIN
    DBMS_LOB.CREATETEMPORARY(FILECONTENT,TRUE,DBMS_LOB.SESSION);
    DBMS_LOB.FILEOPEN(SRC_FILE,DBMS_LOB.FILE_READONLY);
    DBMS_LOB.LOADBLOBFROMFILE (FILECONTENT, SRC_FILE, DBMS_LOB.GETLENGTH(SRC_FILE),
      OFFSET, OFFSET);
    DBMS_LOB.FILECLOSE(SRC_FILE);
    RETURN FILECONTENT;
  END;